import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;
import com.vaadin.v7.ui.ComboBox;
import com.vaadin.v7.ui.Label;
import com.vaadin.v7.ui.TextField;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class WAMCalculator extends AbsoluteLayout {
	protected Button courseoutline;
	protected Button aboutus;
	protected Button myprofile;
	protected Button coursecomplete;
	protected Button dashboard;
	protected Label welcome;
	protected Button wamcalculator;
	protected ComboBox sub1;
	protected ComboBox sub2;
	protected ComboBox sub3;
	protected ComboBox sub4;
	protected TextField sub1uoc;
	protected TextField sub2uoc;
	protected TextField sub3uoc;
	protected TextField sub4uoc;
	protected TextField sub1grade;
	protected TextField sub2grade;
	protected TextField sub3grade;
	protected TextField sub4grade;
	protected Label wam;

	public WAMCalculator() {
		Design.read(this);
	}
}
